export async function GET() {
  return Response.json({
    muscles: {
      pectoralis_major: 0.82,
      deltoid_left: 0.63,
      deltoid_right: 0.67,
      biceps_left: 0.48,
      biceps_right: 0.52,
      triceps_left: 0.62,
      triceps_right: 0.58,
      forearm_flexors_left: 0.41,
      forearm_flexors_right: 0.44,
      forearm_extensors_left: 0.33,
      forearm_extensors_right: 0.36,
      rectus_abdominis_upper: 0.82,
      rectus_abdominis_middle: 0.72,
      rectus_abdominis_lower: 0.56,
      external_oblique_left: 0.45,
      external_oblique_right: 0.48,
      serratus_anterior_left: 0.41,
      serratus_anterior_right: 0.44,
      quadriceps_left: 0.85,
      quadriceps_right: 0.80,
      adductors_left: 0.53,
      adductors_right: 0.49,
      tibialis_anterior_left: 0.62,
      tibialis_anterior_right: 0.60,
      gastrocnemius_left: 0.58,
      gastrocnemius_right: 0.55,
    },
  });
}
