import Link from "next/link";

export const metadata = {
  title: "MuscleSync – AI Fitness Platform",
  description: "AI-powered fitness tracking, personalized workout plans, and real-time progress monitoring.",
};

export default function Home() {
  return (
    <main className="bg-gray-50 text-gray-900">

      {/* NAVBAR */}
      <nav className="fixed top-0 left-0 w-full backdrop-blur bg-white/70 border-b border-gray-200 z-50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold">MuscleSync</h1>
          <div className="flex gap-6">
            <Link href="/login" className="hover:text-blue-600">Login</Link>
            <Link href="/register" className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="pt-32 pb-20 text-center bg-gradient-to-b from-blue-50 to-gray-50">
        <h2 className="text-5xl font-extrabold mb-6">
          Build Your Best Body with <span className="text-blue-600">MuscleSync</span>
        </h2>
        <p className="text-lg max-w-2xl mx-auto mb-10 text-gray-600">
          AI-powered fitness tracking, personalized workout plans, and real-time progress monitoring.
        </p>

        <Link
          href="/register"
          className="px-8 py-4 bg-blue-600 text-white rounded-xl text-lg shadow-lg hover:bg-blue-700"
        >
          Start Free
        </Link>
      </section>

      {/* FEATURES */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <h3 className="text-3xl font-bold text-center mb-12">Why MuscleSync?</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl transition">
            <h4 className="text-xl font-bold mb-3">AI Workout Plans</h4>
            <p className="text-gray-600">Personalized routines generated by advanced AI models.</p>
          </div>

          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl transition">
            <h4 className="text-xl font-bold mb-3">Progress Tracking</h4>
            <p className="text-gray-600">Visual charts and analytics to monitor your fitness journey.</p>
          </div>

          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl transition">
            <h4 className="text-xl font-bold mb-3">Nutrition Guidance</h4>
            <p className="text-gray-600">Smart meal suggestions tailored to your goals.</p>
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <h3 className="text-3xl font-bold text-center mb-12">Pricing</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="p-8 rounded-xl shadow-lg border border-gray-200 bg-white">
            <h4 className="text-2xl font-bold mb-2">Free</h4>
            <p className="text-4xl font-extrabold mb-4">$0</p>
            <ul className="space-y-2 mb-6 text-gray-700">
              <li>• Basic tracking</li>
              <li>• Starter workouts</li>
            </ul>
            <Link href="/register" className="px-6 py-3 bg-blue-600 text-white rounded-lg block text-center hover:bg-blue-700">
              Choose Plan
            </Link>
          </div>

          <div className="p-8 rounded-xl shadow-lg border border-blue-600 bg-blue-50">
            <h4 className="text-2xl font-bold mb-2">Pro</h4>
            <p className="text-4xl font-extrabold mb-4">$9.99/mo</p>
            <ul className="space-y-2 mb-6 text-gray-700">
              <li>• AI workouts</li>
              <li>• Advanced analytics</li>
            </ul>
            <Link href="/register" className="px-6 py-3 bg-blue-600 text-white rounded-lg block text-center hover:bg-blue-700">
              Choose Plan
            </Link>
          </div>

          <div className="p-8 rounded-xl shadow-lg border border-gray-200 bg-white">
            <h4 className="text-2xl font-bold mb-2">Elite</h4>
            <p className="text-4xl font-extrabold mb-4">$19.99/mo</p>
            <ul className="space-y-2 mb-6 text-gray-700">
              <li>• Full analytics</li>
              <li>• Nutrition AI</li>
              <li>• Priority support</li>
            </ul>
            <Link href="/register" className="px-6 py-3 bg-blue-600 text-white rounded-lg block text-center hover:bg-blue-700">
              Choose Plan
            </Link>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-gray-900 text-gray-300 py-12 mt-20">
        <div className="max-w-6xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-10">
          <div>
            <h4 className="text-xl font-bold mb-4 text-white">MuscleSync</h4>
            <p>AI-powered fitness platform.</p>
          </div>
          <div>
            <h4 className="text-lg font-semibold mb-4 text-white">Links</h4>
            <ul className="space-y-2">
              <li><Link href="/login">Login</Link></li>
              <li><Link href="/register">Register</Link></li>
              <li><Link href="/dashboard">Dashboard</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="text-lg font-semibold mb-4 text-white">Social</h4>
            <p>Coming soon.</p>
          </div>
        </div>

        <p className="text-center text-gray-500 mt-10">© 2026 MuscleSync. All rights reserved.</p>
      </footer>
    </main>
  );
}
