import Link from "next/link";

export const metadata = {
  title: "MuscleSync – AI Fitness Platform",
  description: "AI-powered fitness tracking, personalized workout plans, and real-time progress monitoring.",
};

export default function Home() {
  return (
    <main className="bg-gray-50 text-gray-900">

      {/* NAVBAR */}
      <nav className="fixed top-0 left-0 w-full backdrop-blur bg-white/70 border-b border-gray-200 z-50 animate-fadeIn">
        <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold tracking-tight">MuscleSync</h1>
          <div className="flex gap-6">
            <Link href="/login" className="hover:text-blue-600 transition">Login</Link>
            <Link href="/register" className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="pt-32 pb-20 text-center bg-gradient-to-b from-blue-600 to-blue-400 text-white animate-slideUp">
        <h2 className="text-5xl font-extrabold mb-6 drop-shadow-lg">
          Transform Your Body with <span className="text-yellow-300">AI Fitness</span>
        </h2>
        <p className="text-lg max-w-2xl mx-auto mb-10 opacity-90">
          Smart workout plans, real-time analytics, and AI-driven coaching designed for peak performance.
        </p>

        <Link
          href="/register"
          className="px-8 py-4 bg-yellow-300 text-blue-900 rounded-xl text-lg shadow-xl hover:bg-yellow-400 transition"
        >
          Start Free
        </Link>
      </section>

      {/* FEATURES */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <h3 className="text-3xl font-bold text-center mb-12 animate-fadeIn">Why MuscleSync?</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl transition animate-slideUp">
            <h4 className="text-xl font-bold mb-3">AI Workout Plans</h4>
            <p className="text-gray-600">Dynamic routines generated by advanced AI models.</p>
          </div>

          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl transition animate-slideUp delay-200">
            <h4 className="text-xl font-bold mb-3">Progress Tracking</h4>
            <p className="text-gray-600">Charts, analytics, and performance insights.</p>
          </div>

          <div className="p-8 bg-white rounded-xl shadow hover:shadow-xl transition animate-slideUp delay-300">
            <h4 className="text-xl font-bold mb-3">Nutrition AI</h4>
            <p className="text-gray-600">Meal plans tailored to your fitness goals.</p>
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <h3 className="text-3xl font-bold text-center mb-12 animate-fadeIn">Pricing</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="p-8 rounded-xl shadow-lg border border-gray-200 bg-white animate-slideUp">
            <h4 className="text-2xl font-bold mb-2">Free</h4>
            <p className="text-4xl font-extrabold mb-4">$0</p>
            <ul className="space-y-2 mb-6 text-gray-700">
              <li>• Basic tracking</li>
              <li>• Starter workouts</li>
            </ul>
            <Link href="/register" className="px-6 py-3 bg-blue-600 text-white rounded-lg block text-center hover:bg-blue-700 transition">
              Choose Plan
            </Link>
          </div>

          <div className="p-8 rounded-xl shadow-lg border border-blue-600 bg-blue-50 animate-slideUp delay-200">
            <h4 className="text-2xl font-bold mb-2">Pro</h4>
            <p className="text-4xl font-extrabold mb-4">$9.99/mo</p>
            <ul className="space-y-2 mb-6 text-gray-700">
              <li>• AI workouts</li>
              <li>• Advanced analytics</li>
              <li>• Weekly coaching tips</li>
            </ul>
            <Link href="/register" className="px-6 py-3 bg-blue-600 text-white rounded-lg block text-center hover:bg-blue-700 transition">
              Choose Plan
            </Link>
          </div>

          <div className="p-8 rounded-xl shadow-lg border border-yellow-400 bg-yellow-50 animate-slideUp delay-300">
            <h4 className="text-2xl font-bold mb-2">Elite</h4>
            <p className="text-4xl font-extrabold mb-4">$19.99/mo</p>
            <ul className="space-y-2 mb-6 text-gray-700">
              <li>• Full analytics</li>
              <li>• Nutrition AI</li>
              <li>• Priority support</li>
              <li>• Personalized coaching</li>
            </ul>
            <Link href="/register" className="px-6 py-3 bg-yellow-400 text-blue-900 rounded-lg block text-center hover:bg-yellow-500 transition">
              Choose Plan
            </Link>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-gray-900 text-gray-300 py-12 mt-20 animate-fadeIn">
        <div className="max-w-6xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-10">
          <div>
            <h4 className="text-xl font-bold mb-4 text-white">MuscleSync</h4>
            <p>AI-powered fitness platform.</p>
          </div>
          <div>
            <h4 className="text-lg font-semibold mb-4 text-white">Links</h4>
            <ul className="space-y-2">
              <li><Link href="/login">Login</Link></li>
              <li><Link href="/register">Register</Link></li>
              <li><Link href="/dashboard">Dashboard</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="text-lg font-semibold mb-4 text-white">Social</h4>
            <p>Coming soon.</p>
          </div>
        </div>

        <p className="text-center text-gray-500 mt-10">© 2026 MuscleSync. All rights reserved.</p>
      </footer>

      {/* ANIMATIONS */}
      <style>{`
        .animate-fadeIn {
          animation: fadeIn 1s ease forwards;
          opacity: 0;
        }
        .animate-slideUp {
          animation: slideUp 1s ease forwards;
          opacity: 0;
          transform: translateY(20px);
        }
        .delay-200 { animation-delay: 0.2s; }
        .delay-300 { animation-delay: 0.3s; }

        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }

        @keyframes slideUp {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </main>
  );
}
