"use client";

import { motion } from "framer-motion";

export default function Home() {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* NAVBAR */}
      <nav className="flex justify-between items-center px-8 py-6 border-b border-white/10">
        <h1 className="text-2xl font-bold tracking-wide">MuscleSync</h1>
        <div className="flex gap-8 text-lg">
          <a href="/" className="hover:text-orange-400 transition">Home</a>
          <a href="#features" className="hover:text-orange-400 transition">Features</a>
          <a href="#pricing" className="hover:text-orange-400 transition">Pricing</a>
          <a href="/login" className="hover:text-orange-400 transition">Login</a>
          <a href="/register" className="hover:text-orange-400 transition">Register</a>
        </div>
      </nav>

      {/* HERO */}
      <section className="px-8 py-24 text-center">
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-5xl font-extrabold mb-6"
        >
          Build Your Best Body with <span className="text-orange-500">MuscleSync</span>
        </motion.h2>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-xl text-white/70 max-w-2xl mx-auto"
        >
          AI-powered fitness tracking, personalized workout plans, and real-time progress monitoring.
        </motion.p>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mt-10 flex justify-center gap-6"
        >
          <a
            href="/register"
            className="px-8 py-4 bg-orange-600 rounded-xl text-lg font-semibold hover:bg-orange-700 transition"
          >
            Get Started
          </a>
          <a
            href="/login"
            className="px-8 py-4 border border-white/20 rounded-xl text-lg font-semibold hover:bg-white/10 transition"
          >
            Login
          </a>
        </motion.div>

        {/* HERO IMAGE PLACEHOLDER */}
        <div className="mt-20 flex justify-center">
          <div className="w-full max-w-4xl h-72 bg-white/5 rounded-2xl border border-white/10 flex items-center justify-center text-white/40">
            Hero Image / Fitness Illustration
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section id="features" className="px-8 py-24">
        <h3 className="text-4xl font-bold text-center mb-16">Why MuscleSync?</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
          <div className="bg-white/5 p-8 rounded-2xl border border-white/10">
            <h4 className="text-2xl font-semibold mb-4">AI Workout Plans</h4>
            <p className="text-white/70">
              Personalized routines generated by advanced AI models.
            </p>
          </div>

          <div className="bg-white/5 p-8 rounded-2xl border border-white/10">
            <h4 className="text-2xl font-semibold mb-4">Progress Tracking</h4>
            <p className="text-white/70">
              Visual charts and analytics to monitor your fitness journey.
            </p>
          </div>

          <div className="bg-white/5 p-8 rounded-2xl border border-white/10">
            <h4 className="text-2xl font-semibold mb-4">Nutrition Guidance</h4>
            <p className="text-white/70">
              Smart meal suggestions tailored to your goals.
            </p>
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" className="px-8 py-24 bg-white/5 border-t border-white/10">
        <h3 className="text-4xl font-bold text-center mb-16">Pricing</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
          {/* FREE */}
          <div className="bg-black p-8 rounded-2xl border border-white/10">
            <h4 className="text-2xl font-semibold mb-4">Free</h4>
            <p className="text-white/70 mb-6">Basic features for beginners.</p>
            <p className="text-4xl font-bold mb-6">$0</p>
            <a className="px-6 py-3 bg-orange-600 rounded-xl block text-center hover:bg-orange-700 transition">
              Start Free
            </a>
          </div>

          {/* PRO */}
          <div className="bg-black p-8 rounded-2xl border border-white/10">
            <h4 className="text-2xl font-semibold mb-4">Pro</h4>
            <p className="text-white/70 mb-6">Advanced AI workout plans.</p>
            <p className="text-4xl font-bold mb-6">$9.99/mo</p>
            <a className="px-6 py-3 bg-orange-600 rounded-xl block text-center hover:bg-orange-700 transition">
              Upgrade
            </a>
          </div>

          {/* ELITE */}
          <div className="bg-black p-8 rounded-2xl border border-white/10">
            <h4 className="text-2xl font-semibold mb-4">Elite</h4>
            <p className="text-white/70 mb-6">Full analytics + nutrition AI.</p>
            <p className="text-4xl font-bold mb-6">$19.99/mo</p>
            <a className="px-6 py-3 bg-orange-600 rounded-xl block text-center hover:bg-orange-700 transition">
              Go Elite
            </a>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="px-8 py-12 text-center text-white/50 border-t border-white/10">
        © 2026 MuscleSync — All rights reserved.
      </footer>
    </div>
  );
}
