export default function Features() {
  return (
    <section className="py-20 bg-white">
      <div className="max-w-5xl mx-auto text-center">
        <h2 className="text-4xl font-bold mb-10">Why MuscleSync?</h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="p-6 border rounded-xl shadow-sm">
            <h3 className="text-xl font-semibold mb-3">AI Workout Plans</h3>
            <p className="text-gray-600">
              Personalized routines generated by advanced AI models.
            </p>
          </div>

          <div className="p-6 border rounded-xl shadow-sm">
            <h3 className="text-xl font-semibold mb-3">Progress Tracking</h3>
            <p className="text-gray-600">
              Visual charts and analytics to monitor your fitness journey.
            </p>
          </div>

          <div className="p-6 border rounded-xl shadow-sm">
            <h3 className="text-xl font-semibold mb-3">Nutrition Guidance</h3>
            <p className="text-gray-600">
              Smart meal suggestions tailored to your goals.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
